### ISSUE TITLE
A compatible storage

### ISSUE THREAD

**Issue by Nathan1852** [A2Bcorp/RW_A2B#19] opened 2015-01-18 20:47 UTC
It would be nice to have a (big) storage that can be used with the conveyor system, since else the pawns have to sort the items into storage everytime.

**Comment by noone57** [comment] 2015-01-24 02:50
Agreed. Such a feature has been requested for quite some time now ... :-)
What I could envisage is to have the Unloader drop items on the floor on more than just one location. I.e. maybe a 2x3 or 3x3 area. It would still fill up, though, so, that only delays the inevitable. 

I guess the more elegant solution would be to have the Unloader 'detect' adjacent stockpiles and pile them up if possible. But then again, it does not makes sense anymore if the stockpile is too large. 

So, the best approach might be to simply drop items in more spots than just one around the unloaders. What do you think ? 

I'm flat out these days, but will keep this on the to-do list ...

**Comment by TehJoE** [comment] 2015-02-24 06:19
duplicate of #13

**Closed** 2015-04-20 06:08 UTC
Labels: duplicate
