### ISSUE TITLE
Possible performance issues

### ISSUE THREAD

**Issue by TehJoE** [A2Bcorp/RW_A2B#32] opened 2015-02-25 05:16 UTC
from bullet on the ludeon forums:
![I had some errors but these not related with this mod and not caused the same lags before\.
\
Also I use 275x275 map size \(which not recommended\) and at this moment I have lots of different items on the map\
And game restarting seems like slightly helped\. And if screen not focused on the factory\, it\'s helps also \(and if screen movement only in pause\) And yep\, after turning off the factory, all lags are gone\
\
I remember that in the Alpha 8 were similar lags\, but latest mod updatings seems like  to fix these problems\. Last time when I was playing in the alpha 8 I had a lot of conveyors and there was no lags](http://puu.sh/gbG5p/6a53a116d1.png)

**Comment by noone57** [comment] 2015-02-25 05:28
I wonder if this is related to the number of moving parts on the screen ... Maybe on slow computers, this is a problem ? Then of course there's the other mods present that could interfere ... 

Do you get lags if there are many many belts on the map ?

**Comment by TehJoE** [comment] 2015-02-25 06:45
I'm not convinced there's a performance issue with A2B... In my testing there was no FPS drop except at x4 speed (but that always hitches a bit) even with belt structures several times larger than the one presented. But I don't exactly play RimWorld on a microwave oven either ;)

Here's a video of my test build: http://youtu.be/pkFFyCu3Mwk

**Comment by noone57** [comment] 2015-02-25 22:38
Cool video ... ;-) It's going to be hard to troubleshoot if we can't reproduce the bug. But it's clear that many belts can work just fine ...

**Comment by noone57** [comment] 2015-04-18 03:03
Closed as we moved to A10.

**Closed by noone57** 2015-04-18 03:03 UTC
Labels: dubious
